export interface Suplemento {
  id?: number;
  product: string;
  flavors: string[];
  price: number;
  brand: string;
  categoria: CATEOGORIAS;
  descripcion: string;
  image?: string;
}

export interface CatalogoData {
  MERVICK: Suplemento[];
  ENA: Suplemento[];
  STAR: Suplemento[];
}

export const marcas = [
  {
    name: "Todas las marcas",
    image: "/LOGOS/arrow.webp",
    value: "todos",
  },
  {
    name: "ENA",
    image: "/LOGOS/ena.avif",
    value: "ENA",
  },
  {
    name: "STAR",
    image: "/LOGOS/star.avif",
    value: "STAR",
  },
  {
    name: "MERVICK",
    image: "/LOGOS/mervick2.png",
    value: "MERVICK",
  },
]

export const categorias = [
  "todos",
  "proteina",
  "creatina",
  "ganador",
  "aminoacidos",
  "pre-entreno",
  "quemadores",
  "vitaminas",
  "colageno",
  "barras",
  "carbohidratos",
  "energia",
]

export type CATEOGORIAS =
  | "todos"
  | "proteina"
  | "creatina"
  | "ganador"
  | "aminoacidos"
  | "pre-entreno"
  | "quemadores"
  | "vitaminas"
  | "colageno"
  | "barras"
  | "carbohidratos"
  | "energia";

const catalogoData: CatalogoData = {

  ENA: [
    {
      product: "WHEY PROTEIN TRUE MADE 2,05LB",
      descripcion:
        "ENA Sport Proteínas True Made Whey Protein Polvo - Pote - Banana shake 2,05 Lb - 930 g",
      flavors: ["BANANA", "CHOCOLATE", "COOKIES", "FRUTILLA", "VAINILLA"],
      price: 36000,
      brand: "ENA",
      categoria: "proteina",
      image: "/ENA/protein-205.webp",
    },
    {
      product: "WHEY PROTEIN TRUEMADE 5LB",
      descripcion:
        "Truemade Whey Protein 5lb (2.27 Kg)proteina Whey Isolate Ena",
      flavors: ["CHOCOLATE", "VAINILLA"],
      price: 76000,
      brand: "ENA",
      categoria: "proteina",
      image: "/ENA/protein-5lb.webp",
    },
    {
      product: "WHEY PROTEIN TRUEMADE 1LB",
      descripcion:
        "ENA Sport Proteínas True Made Whey Protein Polvo - Pote - Banana shake 1 Lb - 454 g",
      flavors: ["NEUTRO", "CHOCOLATE", "COOKIES", "FRUTILLA", "VAINILLA"],
      price: 22000,
      brand: "ENA",
      categoria: "proteina",
      image: "/ENA/protein-1lb.webp",
    },
    {
      product: "ISOPROT 2LB",
      descripcion:
        "Whey Protein Isolate Isoprot Ena 2lbs Sabor Chocolate Mousse",
      flavors: ["CHOCOLATE", "VAINILLA"],
      price: 69000,
      brand: "ENA",
      categoria: "proteina",
      image: "/ENA/ispoprot.webp",
    },
    {
      product: "WHEY X PRO 1LB",
      descripcion:
        "Whey X Pro (1 Lb) Ena - Proteína Suero De Leche",
      flavors: ["CHOCOLATE", "VAINILLA"],
      price: 25000,
      brand: "ENA",
      categoria: "proteina",
      image: "/ENA/xpro-1lb.webp",
    },
    {
      product: "WHEY X PRO 2LB",
      flavors: ["CHOCOLATE", "VAINILLA"],
      descripcion: "Suplemento en polvo ENA Sport Whey X-Pro proteína sabor double rich chocolate en pote de 907g",
      price: 43000,
      brand: "ENA",
      categoria: "proteina",
      image: "/ENA/xpro-1lb.webp",
    },
    {
      product: "ULTRA MASS 1.5KG",
      flavors: ["CHOCOLATE", "VAINILLA"],
      descripcion: "Ena Super Ultra Mass Chocolate X 1500 Gr Polvo",
      image: "/ENA/mass-1kg.webp",
      price: 28000,
      brand: "ENA",
      categoria: "ganador",
    },
    {
      product: "ULTRA MASS 3KG BIG SIZE",
      flavors: ["CHOCOLATE", "VAINILLA"],
      descripcion: "ENA Sport Ultra Mass Ganador De Peso Y Masa X3kg Sabor Chocolate",
      image: "/ENA/mass-3kg.webp",
      price: 47000,
      brand: "ENA",
      categoria: "ganador",
    },
    {
      product: "STARTER PROTEIN",
      descripcion: "Ena Starter Protein En Polvo Desayuno Proteico Más Energía Sabor Café con leche",
      image: "/ENA/starter.webp",
      flavors: ["CAFE"],
      price: 15300,
      brand: "ENA",
      categoria: "proteina",
    },
    {
      product: "100% WHEY",
      flavors: ["CHOCOLATE", "VAINILLA", "FRUTILLA"],
      descripcion: "Whey Protein 900g Pura 80% Pack Ena Masa Muscular Crossfit Sabor Frutilla",
      image: "/ENA/100.webp",
      price: 29000,
      brand: "ENA",
      categoria: "proteina",
    },
    {
      product: "TM PURE COLLAGEN",
      descripcion: "Truemade Pure Collagen Ena Sport En Polvo 345 Grs Colageno Sabor Blueberry",
      image: "/ENA/colageno.webp",
      flavors: ["NEUTRO", "LIMON", "BLUEBERRY"],
      price: 20150,
      brand: "ENA",
      categoria: "colageno",
    },
    {
      product: "TM WHEY COLLAGEN 2LB",
      descripcion: "Pure Collagen 30 Servicios Ena Colageno Hidrolizado",
      image: "/ENA/colageno.webp",
      flavors: ["CHOCOLATE", "VAINILLA"],
      price: 25000,
      brand: "ENA",
      categoria: "colageno",
    },
    {
      product: "COLAGENO SPORT",
      descripcion: "Colágeno Hidrolizado Ena Sport Articulaciones Y Huesos Sanos Sabor Naranja Pote en Polvo",
      image: "/ENA/colageno-sport.webp",
      flavors: ["NARANJA", "FRUIT PUNCH"],
      price: 21250,
      brand: "ENA",
      categoria: "colageno",
    },
    {
      product: "ENACCIÓN COLAGENO MOVE",
      descripcion: "Enacción Colágeno Move X 30 Comp. Ena Sabor Sin sabor",
      image: "/ENA/enaccion.webp",
      flavors: [],
      price: 10900,
      brand: "ENA",
      categoria: "colageno",
    },
    {
      product: "BETA ALANINE",
      descripcion: "Beta Alanina ENA Pre Work 60 Capsulas",
      image: "/ENA/beta.webp",
      flavors: [],
      price: 8600,
      brand: "ENA",
      categoria: "aminoacidos",
    },
    {
      product: "PRE WAR",
      descripcion: "Pre War 400g Ena Sport - Energizante Pre Entrenamient Sabor Fruit punch",
      image: "/ENA/pre-war.webp",
      flavors: ["FRUIT PUNCH", "LEMONADE"],
      price: 26000,
      brand: "ENA",
      categoria: "pre-entreno",
    },
    {
      product: "CREATINA 300GRS",
      flavors: ["NEUTRO"],
      descripcion: "Suplemento en polvo ENA Sport Creatina micronizada 100% Pura en Doypack de 300g sabor neutro",
      image: "/ENA/creatina.webp",
      price: 28000,
      brand: "ENA",
      categoria: "creatina",
    },
    {
      product: "CREATINA 300GRS SABOR FRUTILLA",
      descripcion: "ENA Sport Monohidrato de Creatina Micronizada 300 g Polvo Doypack Fruit punch",
      image: "/ENA/creatina-frutilla.webp",
      flavors: ["FRUIT PUNCH"],
      price: 29000,
      brand: "ENA",
      categoria: "creatina",
    },
    {
      product: "CREATINA CREAPURE 200GRS",
      flavors: [],
      price: 28000,
      brand: "ENA",
      categoria: "creatina",
      descripcion: "Creatina Creapure Monohidrato Ena Sport En Pote 200grs Sabor Sin sabor",
      image: "/ENA/creapure.webp",
    },
    {
      product: "AMINO FULL LEMONADE",
      flavors: ["LEMONADE"],
      price: 17000,
      brand: "ENA",
      categoria: "aminoacidos",
      descripcion: "True Made Amino Full Ena Aminoácidos Bcaa Cafeína Sabor Lemonade",
      image: "/ENA/amino.webp",
    },
    {
      product: "ENARGY GEL + CAFEÍNA 12",
      descripcion: "Enargy Gel + Cafeina Ena Caja X 12",
      image: "/ENA/energy-1.webp",
      flavors: ["CITRUS", "VAINILLA", "UVA"],
      price: 14000,
      brand: "ENA",
      categoria: "energia",
    },
    {
      product: "ENARGY GEL 12",
      descripcion: "Enargy Gel X 12",
      image: "/ENA/energy-1.webp",
      flavors: ["LIMON", "VAINILLA", "FRUTILLA"],
      price: 13000,
      brand: "ENA",
      categoria: "energia",
    },
    {
      product: "CARBO ENERGY",
      descripcion: "Carbo Energy 540 Gr Ena Bebida Deportiva Isotónica En Polvo Sabor Fruit punch",
      image: "/ENA/carbo.webp",
      flavors: ["BLUEBERRY", "FRUIT PUNCH"],
      price: 12000,
      brand: "ENA",
      categoria: "carbohidratos",
    },
    {
      product: "MULTIVITAMINICO",
      descripcion: "Multivitamin Ena Sport - Minerales, Vitaminas, Cafeína Sabor Neutro",
      image: "/ENA/multi.webp",
      flavors: [],
      price: 14000,
      brand: "ENA",
      categoria: "vitaminas",
    },
    {
      product: "PROTEIN BAR",
      descripcion: "Ena Protein Bar Caja X16 Un. - Sabor Banana Split",
      image: "/ENA/barras.webp",
      flavors: ["LIMON", "FRUTILLA", "COCO CON DDL", "CHOCOLATE", "BANANA"],
      price: 24000,
      brand: "ENA",
      categoria: "barras",
    },
  ],
  STAR: [
    {
      product: "WHEY PROTEIN DOYPACK 2LBS",
      descripcion:
        "Whey Protein Doypack 2lbs (907g)proteina Whey Isolate Star",
      flavors: ["BANANA", "CHOCOLATE", "COOKIES", "FRUTILLA", "VAINILLA"],
      price: 33900,
      brand: "STAR",
      categoria: "proteina",
      image: "/STAR/whey-doypack.webp",
    },
    {
      product: "WHEY PROTEIN 2LBS",
      descripcion: "Whey Protein 2lbs (907g)proteina Whey Isolate Star",
      image: "/STAR/whey-1kg.webp",
      flavors: ["BANANA", "CHOCOLATE", "COOKIES", "FRUTILLA", "VAINILLA"],
      price: 36900,
      brand: "STAR",
      categoria: "proteina",
    },
    {
      product: "WHEY PROTEIN 3KG",
      flavors: ["BANANA", "CHOCOLATE", "COOKIES", "FRUTILLA", "VAINILLA"],
      price: 112000,
      brand: "STAR",
      categoria: "proteina",
      descripcion: "Suplemento en Polvo Star Nutrition Platinum Whey Protein Sabor Chocolate Suizo en Sachet de 3kg",
      image: "/STAR/whey-3kg.webp",
    },
    {
      product: "MUTANT MASS 1.5 KG",
      descripcion: "Suplemento en polvo Star Nutrition Proteínas sabor cookies & cream x 5kg",
      image: "/STAR/mutant.webp",
      flavors: ["BANANA", "CHOCOLATE", "COOKIES", "FRUTILLA", "VAINILLA"],
      price: 27000,
      brand: "STAR",
      categoria: "ganador",
    },
    {
      product: "MUTANT MASS 5 KG",
      descripcion: "Suplemento en polvo Star Nutrition Proteínas sabor cookies & cream x 5kg",
      image: "/STAR/mutant.webp",
      flavors: ["BANANA", "CHOCOLATE", "COOKIES", "FRUTILLA", "VAINILLA"],
      price: 74000,
      brand: "STAR",
      categoria: "ganador",
    },
    {
      product: "JUST PLANT 2LB",
      descripcion: "Just Plant Protein Star Nutrition Vegana 2lb Sin Sabor",
      image: "/STAR/just-plant.webp",
      flavors: [],
      price: 33000,
      brand: "STAR",
      categoria: "proteina",
    },
    {
      product: "JUST WHEY 2LB",
      descripcion: "Just Whey Protein 2lbs Sin Sabor Star Nutrition",
      image: "/STAR/just-whey.webp",
      flavors: [],
      price: 35000,
      brand: "STAR",
      categoria: "proteina",
    },
    {
      product: "WHEY ISOLATE 2LB",
      descripcion: "Proteina 100% Isolada en Pote Star Nutrition X 2 Lb - Libre Lactosa",
      image: "/STAR/isolate.webp",
      flavors: ["BANANA", "CHOCOLATE", "FRUTILLA", "VAINILLA"],
      price: 68000,
      brand: "STAR",
      categoria: "proteina",
    },
    {
      product: "NITRO WHEY 2LB",
      descripcion: "Star Nutrition Nitro Whey Proteina Sabor Vainilla X 2lb",
      image: "/STAR/nitro.webp",
      flavors: ["CHOCOLATE", "FRUTILLA", "VAINILLA"],
      price: 43000,
      brand: "STAR",
      categoria: "proteina",
    },
    {
      product: "CREATINA 150GRS",
      descripcion: "Star Nutrition Creatina Monohidrato Suplemento X 150gr",
      image: "/STAR/creatina-150.webp",
      flavors: [],
      price: 16000,
      brand: "STAR",
      categoria: "creatina",
    },
    {
      product: "CREATINA 300GRS",
      descripcion: "Star Nutrition Creatina Monohidrato Suplemento X 300gr",
      image: "/STAR/creatina-300.webp",
      flavors: [],
      price: 29000,
      brand: "STAR",
      categoria: "creatina",
    },
    {
      product: "CREATINA 300GRS DOYPACK",
      descripcion: "Star Nutrition Creatina Monohidrato Suplemento X 300gr",
      image: "/STAR/creatina-300.webp",
      flavors: [],
      price: 27000,
      brand: "STAR",
      categoria: "creatina",
    },
    {
      product: "CREATINA 500GRS",
      descripcion: "Suplemento Star Nutrition Ultramicronized Creatina Monohydrate de 500g - Polvo",
      image: "/STAR/creatina-500.webp",
      flavors: [],
      price: 43000,
      brand: "STAR",
      categoria: "creatina",
    },
    {
      product: "CREATINA 1KG",
      descripcion: "Suplemento en Polvo Star Nutrition Creatine Monohydrate en Pote de 1kg",
      image: "/STAR/creatina-1kg.webp",
      flavors: [],
      price: 79000,
      brand: "STAR",
      categoria: "creatina",
    },
    {
      product: "ARGININA",
      descripcion: "Arginina Gh Star Nutrition 150g en Polvo Sin sabor",
      image: "/STAR/arginina.webp",
      flavors: [],
      price: 14000,
      brand: "STAR",
      categoria: "aminoacidos",
    },
    {
      product: "GLUTAMINE 150GRS",
      descripcion: "Star Nutrition L-glutamina En Polvo - Pote 150g Sabor Sin sabor",
      image: "/STAR/gluta-150.webp",
      flavors: [],
      price: 15000,
      brand: "STAR",
      categoria: "aminoacidos",
    },
    {
      product: "GLUTAMINE 300GRS",
      descripcion: "Star Nutrition L-glutamina En Polvo - Pote 300g Sabor Sin sabor",
      image: "/STAR/gluta-300.webp",
      flavors: [],
      price: 25000,
      brand: "STAR",
      categoria: "aminoacidos",
    },
    {
      product: "BCAA 2000",
      descripcion: "Bcaa 2000 X 120 Caps Star Nutrition Aminoácidos Ramificados Sabor Sin sabor",
      image: "/STAR/bcaa.webp",
      flavors: [],
      price: 15000,
      brand: "STAR",
      categoria: "aminoacidos",
    },
    {
      product: "HYDROPLUS ENDURANCE",
      descripcion: "Hydro Plus Endurance 700gr Star Nutrition Sabor Blue Raz",
      image: "/STAR/hydro.webp",
      flavors: ["BLUE RAZ", "LIMA-LIMON", "NARANJA"],
      price: 15000,
      brand: "STAR",
      categoria: "carbohidratos",
    },
    {
      product: "TNT-DYNAMITE",
      descripcion: "Tnt Dynamite Star Nutrition 240 Gr Pre Entreno Sabor Açai Power",
      image: "/STAR/tnt.webp",
      flavors: ["ACAI", "GRAPE", "BLUE RAZ", "CITRUS SLUSH"],
      price: 20000,
      brand: "STAR",
      categoria: "pre-entreno",
    },
    {
      product: "PUMP V8",
      descripcion: "Pump V8 Star Nutrition 240 Gr Pre Entreno",
      image: "/STAR/v8.webp",
      flavors: ["ACAI", "GRAPE", "LIMON", "WATERMELON"],
      price: 25000,
      brand: "STAR",
      categoria: "pre-entreno",
    },
    {
      product: "PUMP 3D RIPPED",
      descripcion: "Pump 3d Ripped 315 Gr Star Nutrition Pre Entreno Quemador",
      image: "/STAR/3d.webp",
      flavors: ["FRUTILLA-LIMA", "LIMON"],
      price: 29000,
      brand: "STAR",
      categoria: "pre-entreno",
    },
    {
      product: "BETA ALANINA",
      descripcion: "Beta Alanina 300g Star Nutrition Sin sabor",
      image: "/STAR/alanina.webp",
      flavors: [],
      price: 21000,
      brand: "STAR",
      categoria: "aminoacidos",
    },
    {
      product: "CAFFEINE 200MG 30 CAPS",
      descripcion: "Caffeine 200mg Star Nutrition 30 Cápsulas Sin sabor",
      image: "/STAR/caffeine.webp",
      flavors: [],
      price: 6600,
      brand: "STAR",
      categoria: "pre-entreno",
    },
    {
      product: "THERMO FUEL",
      descripcion: "Thermo Fuel Max 120 Caps Star Nutrition Quemador Termogénico en frasco Sin sabor",
      image: "/STAR/thermo.webp",
      flavors: [],
      price: 17000,
      brand: "STAR",
      categoria: "quemadores",
    },
    {
      product: "MAGNESIO 60 CAPS",
      descripcion: "Citrato De Magnesio 500grs X 60 Capsulas - Star Nutrition Sabor Sin sabor",
      image: "/STAR/magnesio-60.webp",
      flavors: [],
      price: 12500,
      brand: "STAR",
      categoria: "vitaminas",
    },
    {
      product: "MAGNESIO 500GRS",
      descripcion: "Citrato De Magnesio En Polvo 500gramos - Star Nutrition Sabor Sin sabor",
      image: "/STAR/magnesio-500.webp",
      flavors: [],
      price: 25000,
      brand: "STAR",
      categoria: "vitaminas",
    },
    {
      product: "VITAMINA C",
      descripcion: "Vitamina C Capsulas",
      image: "/STAR/vitamina-c.webp",
      flavors: [],
      price: 7000,
      brand: "STAR",
      categoria: "vitaminas",
    },
    {
      product: "IRON PACK MULTIVITAMIN",
      descripcion: "Iron Pack Multivitamin - 44 Serv - 383 Gr - Star Nutrition Sabor Fruit Puch",
      image: "/STAR/iron-pack.webp",
      flavors: ["FRUIT PUNCH"],
      price: 83000,
      brand: "STAR",
      categoria: "vitaminas",
    },
    {
      product: "ALL-IN-ONE VITAMIN",
      descripcion: "Multivitamin All In One X60 Caps - Star Nutrition Sabor Sin sabor",
      image: "/STAR/all-one.webp",
      flavors: [],
      price: 17000,
      brand: "STAR",
      categoria: "vitaminas",
    },
    {
      product: "CITRULLINE",
      descripcion: "Oxido Nitrico L Citrulline Malate 300 Gr Star Nutrition Sabor Sin sabor",
      image: "/STAR/citrulline.webp",
      flavors: [],
      price: 47000,
      brand: "STAR",
      categoria: "aminoacidos",
    },
    {
      product: "COLLAGEN HIDROLIZADO",
      descripcion: "Colageno Hydrolizado X210 Gr. Suplemento Sabor Limón - Star Nutrition",
      image: "/STAR/colageno.webp",
      flavors: ["LIMON"],
      price: 17000,
      brand: "STAR",
      categoria: "colageno",
    },
    {
      product: "COLLAGEN WHEY 2LB",
      descripcion: "Collagen Whey Protein 2 Lb (prote+ Colageno)- Star Nutrition",
      image: "/STAR/collagen-wehy.webp",
      flavors: ["CHOCOLATE", "VAINILLA"],
      price: 32000,
      brand: "STAR",
      categoria: "colageno",
    },
    {
      product: "JUST CARB",
      descripcion: "Just Carbs 1 Kg Star Nutrition Energia Y Resistencia Sabor Neutro",
      image: "/STAR/carbs.webp",
      flavors: [],
      price: 15000,
      brand: "STAR",
      categoria: "carbohidratos",
    },
  ], 
  MERVICK: [
    {
      product: "WHEY PROTEIN 2LBS",
      flavors: ["CHOCOLATE", "VAINILLA", "FRUTILLA"],
      descripcion:
        "2 libras de proteína de suero de leche con sabor a chocolate, vainilla y frutilla.",
      price: 28000,
      brand: "MERVICK",
      categoria: "proteina",
      image: "/MERVICK/protein-2lbs.webp",
    },
    {
      product: "WHEY PROTEIN 3KG",
      flavors: ["CHOCOLATE", "VAINILLA", "FRUTILLA"],
      descripcion:
        "3 kilos de proteína de suero de leche con sabor a chocolate, vainilla y frutilla.",
      price: 68000,
      brand: "MERVICK",
      categoria: "proteina",
      image: "/MERVICK/protein-3kg.webp",
    },
    {
      product: "WHEY PROTEIN 3KG 3 SABORES MIX",
      flavors: ["MIX SABORES"],
      descripcion: "Mervick Lab Whey Protein X 3kg Proteína De Suero 3 Sabores",
      price: 70000,
      brand: "MERVICK",
      categoria: "proteina",
      image: "/MERVICK/protein-3kg.webp",
    },
    {
      product: "WHEY PROTEIN BAR 65G",
      flavors: ["FRAMBUESA", "CHOCOLATE", "BANANA", "LIMON"],
      descripcion:
        "Suplemento en barra MervickLab Carbohidratos sabor chocolate x 65g 12 unidades por caja",
      price: 16000,
      brand: "MERVICK",
      categoria: "barras",
      image: "/MERVICK/barritas-65.webp",
    },
    {
      product: "WHEY PROTEIN BAR 46G",
      flavors: ["FRUTOS ROJOS", "CHOCOLATE DARK", "LEMON PIE", "BANANA"],
      descripcion:
        "Barra Mervicklab Protein Bar Dark Chocolate 12 Uds X 46g Sabor Chocolate negro",
      price: 14000,
      brand: "MERVICK",
      categoria: "barras",
      image: "/MERVICK/barritas-46.webp",
    },
    {
      product: "LOW CARB PROTEIN",
      flavors: ["FRUTOS ROJOS", "CHOCOLATE COFFE"],
      price: 18000,
      descripcion:
        "Whey Low Carb Protein Bar Banana 12 Uds X 46g Frutos Rojos",
      brand: "MERVICK",
      categoria: "barras",
      image: "/MERVICK/low-carb.webp",
    },
    {
      product: "MULTIVITAMINICO",
      flavors: [],
      price: 12000,
      brand: "MERVICK",
      descripcion: "Multivitaminico Mervick Lab 120 Capsulas Sabor Sin sabor",
      categoria: "vitaminas",
      image: "/MERVICK/multivitaminico.webp",
    },
    {
      product: "GEL ENERGY CON CAFEÍNA",
      flavors: ["FRUTOS ROJOS", "NARANJA", "LIMON", "MANZANA"],
      price: 13000,
      descripcion:
        "Gel Mervick Repositor Energetico Aminoacidos Sabor Frutos Rojos",
      brand: "MERVICK",
      categoria: "energia",
      image: "/MERVICK/gel.webp",
    },
    {
      product: "GEL RACE SIN CAFEINA",
      flavors: ["FRUTOS ROJOS", "NARANJA", "LIMON", "MANZANA"],
      price: 12000,
      descripcion: "Gel Mervick Repositor Energetico sin cafeina",
      brand: "MERVICK",
      categoria: "energia",
      image: "/MERVICK/gel-sin-cafeina.webp",
    },
    {
      product: "COLAGENO SPORT 330 GRS",
      descripcion:
        "Mervick Lab Colágeno Sport Hidrolizado Suplemento 330 Grs. Sabor Frutos rojos",
      flavors: ["FRUTOS ROJOS"],
      price: 22000,
      brand: "MERVICK",
      categoria: "colageno",
      image: "/MERVICK/colageno.webp",
    },
  ],
};

// Función para obtener todos los suplementos con categorías asignadas
export const obtenerTodosLosSuplementos = (): Suplemento[] => {
  const todosLosSuplementos = [
    ...catalogoData.STAR,
    ...catalogoData.ENA,
    ...catalogoData.MERVICK  ,
  ];

  // Asignar un ID único a cada suplemento
  const suplementosConId = todosLosSuplementos.map((suplemento, index) => ({
    ...suplemento,
    id: index + 1,
  }));

  return suplementosConId;
};

export default catalogoData;